version: "3.4"

services:

  # Database
  bookstore-mysql-db:
    image: ${MYSQL_DOCKER_IMAGE_NAME}
    container_name: ${MYSQL_DOCKER_CONTAINER_NAME}
    hostname: ${MYSQL_DOCKER_HOSTNAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "${MYSQL_PORT}"
    volumes:
      - ${MYSQL_DB_VOLUME_NAME}:/var/lib/mysql
    networks:
      - ${APP_NETWORK_NAME}

  # Database Manager
  adminer:
    image: ${ADMINER_IMAGE_NAME}
    container_name: ${ADMINER_CONTAINER_DOCKER_NAME}
    hostname: ${ADMINER_HOST_NAME}
    environment:
      ADMINER_DEFAULT_SERVER: ${MYSQL_DOCKER_HOSTNAME}
      ADMINER_DESIGN: pepa-linha
      ADMINER_PLUGINS: tables-filter tinymce
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    expose:
      - ${ADMINER_PORT}
    networks:
      - ${APP_NETWORK_NAME}

  # Core services
  bookstore-consul-discovery:
    image: ${CONSUL_DISCOVERY_IMAGE_NAME}
    container_name: ${CONSUL_DISCOVERY_DOCKER_CONTAINER_NAME}
    hostname: ${CONSUL_DISCOVERY_HOST_NAME}
    restart: always
    ports:
      - "${CONSUL_DISCOVERY_PORT}:8500"
    networks:
      - ${APP_NETWORK_NAME}

  # Tracing service
  bookstore-zipkin:
    image: ${ZIPKIN_SERVICE_IMAGE_NAME}
    container_name: ${ZIPKIN_SERVICE_DOCKER_CONTAINER_NAME}
    hostname: ${ZIPKIN_SERVICE_HOST_NAME}
    ports:
      - "${ZIPKIN_SERVICE_PORT}:9411"
    networks:
      - ${APP_NETWORK_NAME}

  bookstore-influxdb:
    image: ${INFLUXDB_SERVICE_IMAGE_NAME}
    container_name: ${INFLUXDB_SERVICE_DOCKER_CONTAINER_NAME}
    hostname: ${INFLUXDB_SERVICE_HOST_NAME}
    volumes:
      - ${INFLUXDB_SERVICE_VOLUME_NAME}:/var/lib/influxdb
    ports:
      - "${INFLUXDB_SERVICE_PORT}:8086"
    networks:
      - ${APP_NETWORK_NAME}

  bookstore-zuul-api-gateway-server:
    build:
      context: ${API_GATEWAY_SERVICE_NAME}
      dockerfile: local.Dockerfile
    image: ${API_GATEWAY_SERVICE_IMAGE_NAME}
    container_name: ${API_GATEWAY_SERVICE_DOCKER_CONTAINER_NAME}
    hostname: ${API_GATEWAY_SERVICE_HOST_NAME}
    volumes:
      - ./${API_GATEWAY_SERVICE_DIRECTORY_NAME}:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    networks:
      - ${APP_NETWORK_NAME}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=${API_GATEWAY_SERVICE_PORT}
      - ZIPKIN_HOST=bookstore-zipkin:9411
    ports:
      - ${API_GATEWAY_SERVICE_PORT}:8765
      - ${API_GATEWAY_SERVICE_DEV_TOOL_LIVE_RELOAD_PORT}:35729
      - ${API_GATEWAY_SERVICE_DEV_TOOL_REMOTE_DEBUG_PORT}:5005

  bookstore-account-service:
    build:
      context: ${ACCOUNT_SERVICE_NAME}
      dockerfile: local.Dockerfile
    image: ${ACCOUNT_SERVICE_IMAGE_NAME}
    container_name: ${ACCOUNT_SERVICE_DOCKER_CONTAINER_NAME}
    hostname: ${ACCOUNT_SERVICE_HOST_NAME}
    volumes:
      - ./${ACCOUNT_SERVICE_DIRECTORY_NAME}:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    networks:
      - ${APP_NETWORK_NAME}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=${ACCOUNT_SERVICE_PORT}
      - ZIPKIN_HOST=bookstore-zipkin:9411
    ports:
      - ${ACCOUNT_SERVICE_PORT}:4001
      - ${ACCOUNT_SERVICE_DEV_TOOL_LIVE_RELOAD_PORT}:35729
      - ${ACCOUNT_SERVICE_DEV_TOOL_REMOTE_DEBUG_PORT}:5005

  bookstore-billing-service:
    build:
      context: ${BILLING_SERVICE_NAME}
      dockerfile: local.Dockerfile
    image: ${BILLING_SERVICE_IMAGE_NAME}
    container_name: ${BILLING_SERVICE_DOCKER_CONTAINER_NAME}
    hostname: ${BILLING_SERVICE_HOST_NAME}
    volumes:
      - ./${BILLING_SERVICE_DIRECTORY_NAME}:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    networks:
      - ${APP_NETWORK_NAME}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=${BILLING_SERVICE_PORT}
      - ZIPKIN_HOST=bookstore-zipkin:9411
    ports:
      - ${BILLING_SERVICE_PORT}:5001
      - ${BILLING_SERVICE_DEV_TOOL_LIVE_RELOAD_PORT}:35729
      - ${BILLING_SERVICE_DEV_TOOL_REMOTE_DEBUG_PORT}:5005

  bookstore-catalog-service:
    build:
      context: ${CATALOG_SERVICE_NAME}
      dockerfile: local.Dockerfile
    image: ${CATALOG_SERVICE_IMAGE_NAME}
    container_name: ${CATALOG_SERVICE_DOCKER_CONTAINER_NAME}
    hostname: ${CATALOG_SERVICE_HOST_NAME}
    volumes:
      - ./${CATALOG_SERVICE_DIRECTORY_NAME}:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    networks:
      - ${APP_NETWORK_NAME}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=${CATALOG_SERVICE_PORT}
      - ZIPKIN_HOST=bookstore-zipkin:9411
    ports:
      - ${CATALOG_SERVICE_PORT}:6001
      - ${CATALOG_SERVICE_DEV_TOOL_LIVE_RELOAD_PORT}:35729
      - ${CATALOG_SERVICE_DEV_TOOL_REMOTE_DEBUG_PORT}:5005

  bookstore-order-service:
    build:
      context: ${ORDER_SERVICE_NAME}
      dockerfile: local.Dockerfile
    image: ${ORDER_SERVICE_IMAGE_NAME}
    container_name: ${ORDER_SERVICE_DOCKER_CONTAINER_NAME}
    hostname: ${ORDER_SERVICE_HOST_NAME}
    volumes:
      - ./${ORDER_SERVICE_DIRECTORY_NAME}:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    networks:
      - ${APP_NETWORK_NAME}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=${ORDER_SERVICE_PORT}
      - ZIPKIN_HOST=bookstore-zipkin:9411
    ports:
      - ${ORDER_SERVICE_PORT}:7001
      - ${ORDER_SERVICE_DEV_TOOL_LIVE_RELOAD_PORT}:35729
      - ${ORDER_SERVICE_DEV_TOOL_REMOTE_DEBUG_PORT}:5005

  bookstore-payment-service:
    build:
      context: ${PAYMENT_SERVICE_NAME}
      dockerfile: local.Dockerfile
    image: ${PAYMENT_SERVICE_IMAGE_NAME}
    container_name: ${PAYMENT_SERVICE_DOCKER_CONTAINER_NAME}
    hostname: ${PAYMENT_SERVICE_HOST_NAME}
    volumes:
      - ./${PAYMENT_SERVICE_DIRECTORY_NAME}:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    networks:
      - ${APP_NETWORK_NAME}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=${PAYMENT_SERVICE_PORT}
      - ZIPKIN_HOST=bookstore-zipkin:9411
    ports:
      - ${PAYMENT_SERVICE_PORT}:8001
      - ${PAYMENT_SERVICE_DEV_TOOL_LIVE_RELOAD_PORT}:35729
      - ${PAYMENT_SERVICE_DEV_TOOL_REMOTE_DEBUG_PORT}:5005

volumes:
  bookstore-db-volume:
  booksture-influxdb-volume:

networks:
  bookstore-app-network:
    driver: bridge