server:
  port: ${SERVER_PORT:6001}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-catalog-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    table: catalog_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9

  main:
    allow-bean-definition-overriding: true

  hateoas:
    use-hal-as-default-json-media-type: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.wolverine.solutions.*: DEBUG