server:
  port: ${BILLING_SERVICE_PORT:5001}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-billing-service
    message-timeout: 10

  sleuth:
    sampler:
      probability: 1.0

  jpa:
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          time_zone: UTC

  main:
    allow-bean-definition-overriding: true

  hateoas:
    use-hal-as-default-json-media-type: false

  datasource:
    dbcp2:
      validation-query: SELECT 1;
    tomcat:
      validation-interval: 80000
    initialization-mode: always
    data: classpath*:data.sql

logging:
  level:
    com.wolverine.solutions.*: DEBUG

management:
  endpoint:
    hystrix:
      stream:
        enabled: true