server:
  port: ${SERVER_PORT:5001}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-billing-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  flyway:
    table: billing_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9
    enabled: off
  main:
    allow-bean-definition-overriding: true
  hateoas:
    use-hal-as-default-json-media-type: false

logging:
  level:
    com.wolverine.solutions.*: DEBUG

management:
  endpoint:
    hystrix:
      stream:
        enabled: true