spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:bookstore_db_account;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    url: jdbc:h2:file:./file-based-db/database_h2/bookstore_db_account;AUTO_SERVER=true
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console