spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  r2dbc:
    url: r2dbc:pool:h2:bookstore_db_account:///default?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
  #    jdbc:h2:tcp://localhost:9092/bookstore_db_account:default
  datasource:
    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:bookstore_db_account;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  #    url: jdbc:h2:./file-based-db/database_h2/bookstore_db_account;AUTO_SERVER=true
  #    username: sa
  #    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console