spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:bookstore_db_payment;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file./file-based-db/database_h2/bookstore_db_payment;AUTO_SERVER=true
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console