server:
  port: ${SERVER_PORT:8001}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

service:
  stripeKey: sk_test_51HyGx6G9R9y827ntfKTizO243LzKHnaNIucO8i7apU0zuTIE5iNAes6l64aoWczGwiCnnBNsvvrgS95nfpbWa2cw00FnScmrhd

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-payment-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    table: payment_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9
  main:
    allow-bean-definition-overriding: true
  hateoas:
    use-hal-as-default-json-media-type: false

logging:
  level:
    com.wolverine.solutions.*: DEBUG

management:
  endpoint:
    hystrix:
      stream:
        enabled: true